#!/bin/sh
PID=/tmp/shairport.pid

case $1 in
	start)
		shairport -P $PID -m tinysvcmdns -d -o alsa -- -d hw:1,0
		;;
	stop)
		# Kill -9 shairport to keep it from muting the volume. FIXME.
		[ -f $PID ] && kill -9 `cat $PID`
		rm -f $PID 2>/dev/null
		;;
	*)
		echo   "usage:	$0 <start|stop>"
		exit 1
		;;
esac
